version: "2"

run:
  timeout: 5m
  # інші run-опції

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - cyclop
    - misspell
    # revive чи інші, за потреби

linters-settings:
  # **Цю секцію або перейменуйте у linters.settings** якщо це правильне місце згідно документації
  cyclop:
    max-complexity: 15
  revive:
    confidence: 0.8

issues:
  exclude-files:
    - "_test\\.go"   # або які файли виключати
  exclude-rules:
    - linters:
        - cyclop
      text: "some text to exclude"
  # інші опції як exclude-patterns, include, etc.

output:
  formats:
    - format: colored-line-number
      # path або інші підопції
  print-issued-lines: true
  print-linter-name: true
  # інші опції як sort-results, path-prefix тощо
