version: "2"

run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - misspell

issues:
  max-issues-per-linter: 50
  max-same-issues: 3

severity:
  default: "warning"