version: 2

run:
  timeout: 5m
  go: "1.25"

linters-settings:
  cyclop:
    max-complexity: 15
  
  revive:
    confidence: 0.8

linters:
  enable:
    # Default enabled linters (explicit for clarity)
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Additional useful linters
    - bodyclose
    - cyclop
    - misspell
    - revive
    - whitespace

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - cyclop
        - errcheck
        - revive

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true